name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  PROJECT_NAME: "DXCam_CPP"

jobs:
  build:
    strategy:
      matrix:
        build_type: [ "Debug", "Release", "RelWithDebInfo" ]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Ninja
        run: choco install ninja -y

      - name: Install OpenCV
        run: choco install opencv -y

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Configure CMake
        run: >
          cmake
          -B ${{github.workspace}}/build
          -G Ninja
          "-DCMAKE_C_COMPILER=cl.exe"
          "-DCMAKE_CXX_COMPILER=cl.exe"
          "-DOpenCV_DIR=C:/Tools/opencv/build"
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PROJECT_NAME}}-${{matrix.build_type}}
          path: ${{github.workspace}}/build/install
